files: 'soldatova*'
repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [--skip-string-normalization, --line-length=100]
        language_version: python3.10

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: flake8
        args: [--config=.flake8]
        language_version: python3.10
